// src/components/Breadcrumbs.svelte
<script lang="ts">
	import { page } from '$app/stores'

	const paths = () => {
		const breadcrumbs: { label: string; href: string }[] = []
		for (const path of $page.params.notes.split('/')) {
			const prev = breadcrumbs[breadcrumbs.length - 1]
			breadcrumbs.push({
				label: path,
				href: prev ? `${prev.href}/${path}` : `/${path}`
			})
		}
		return breadcrumbs
	}

	const breadcrumbs = $derived(paths())
</script>

<nav>
	{#each breadcrumbs as { label, href }, index}
		<a class:active={$page.url.pathname === encodeURI(href)} {href}>
			{decodeURIComponent(label)}
		</a>
		{#if index < breadcrumbs.length - 1}
			<span>/</span>
		{/if}
	{/each}
</nav>

<style>
	nav {
		display: flex;
		user-select: none;
		/* gap: 0.267rem; */
		align-items: center;
		scrollbar-width: none;
		overflow-x: scroll;
		font-size: 0.867rem;
		color: var(--text-secondary);
	}
	a {
		display: inline-flex;
		cursor: pointer;
		/* border-radius: 0.375rem; */
		border-radius: 0.267rem;
		/* padding: 0.125rem 0.375rem; */
		padding: 0.133rem 0.267rem;
		white-space: nowrap;
		line-height: initial;
	}
	a:hover {
		background-color: var(--border-secondary);
		color: var(--text-primary);
	}
	.active {
		color: var(--active-breadcrumb);
	}
	.active:hover {
		background-color: initial;
		color: var(--active-breadcrumb);
	}
	span {
		color: var(--background-quaternary);
		padding: 2px 1px;
	}
</style>

// src/components/Breadcrumbs.tsx
import { Show, For } from "solid-js"
import { A, useParams, useLocation, useMatch } from "@solidjs/router"
import styles from "./breadcrumbs.module.css"

const createPaths = () => {
	const params = useParams() // already URI-encoded

	const paths = params.note?.split("/")

	if (!paths) return

	let breadcrumbs: { label: string; href: string }[] = []

	for (const path of paths) {
		const prev = breadcrumbs[breadcrumbs.length - 1]
		breadcrumbs.push({
			label: path,
			href: prev ? prev.href + `/${path}` : `/${path}`
		})
	}
	return breadcrumbs
}

const Breadcrumbs = () => (
	<Show when={createPaths()}>
		{(paths) => (
			<nav class={styles.breadcrumbs}>
				<For each={paths()}>
					{(path, index) => (
						<>
							<A
								class={styles.breadcrumb}
								href={path.href}
								activeClass="activeBreadcrumb"
								end={true}
							>
								{decodeURIComponent(path.label)}
							</A>
							<Show when={index() < paths().length - 1}>
								<span
									style={{
										"user-select": "none",
										color: "var(--text-secondary)"
									}}
								>
									/
								</span>
							</Show>
						</>
					)}
				</For>
			</nav>
		)}
	</Show>
)

export default Breadcrumbs
